<?php
/**
 * @file
 * Custom user interface for the FLAT data repository
 */

/**
 * Implements hook_help().
 */
function flat_deposit_ui_help($path, $arg){
    switch ($path){
        case 'admin/help#flat_deposit_ui':{
            $ret_val = '<h3>' . t('About') . '</h3>';
            $ret_val = '<p>' . t('The FLAT deposit UI module is designed to manage the project data of each institutes employee') . '</p>';
            return $ret_val;
            break;
        }
    }

}

/**
 * Implements hook_permission().
 */
function flat_deposit_ui_permission()
{
    return array(
        'upload' => array(
            'title' => t('Upload'),
            'description' => t('Upload data to the FLAT deposit')),
        'view' => array(
            'title' => t('View'),
            'description' => t('View files uploaded to the FLAT deposit')),
        'manage' => array(
            'title' => t('Manage'),
            'description' => t('Manage files uploaded to the FLAT deposit')),
       'commit' => array(
            'title' => t('Commit'),
            'description' => t('Commit changes to FLAT deposit')),


    );
}


/**
 * Implements hook_menu().
 */
function flat_deposit_ui_menu()
{
    $items = array();

    // Admin configuration group
    $items['admin/config/flat_deposit_ui'] = array(
        'title' => 'FLAT deposit UI',
        'description' => 'Administer FLAT deposit user interface',
        'access arguments' => array ('administer FLAT deposit UI'),
    );

    // Admin configuration - Upload settings
    $items['admin/config/flat_deposit_ui/manage'] = array(
        'title' => 'Customize settings',
        'description' => 'Administer FLAT deposit settings',
        'access arguments' => array ('administer FLAT deposit UI'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'flat_deposit_ui_admin_form'),
    );
    // Page for view content
    $items['view'] = array(
        'title' => 'View uploaded data',
        'page callback' => 'flat_deposit_ui_view_info',
        'access callback' => TRUE,
        'page arguments' => array(
            'content' => 'Under construction'),
    );
    // Page for manage bundles
    $items['managebundles'] = array(
        'title' => 'Manage bundles',
        'page callback' => 'flat_deposit_ui_view_info',
        'access callback' => TRUE,
        'page arguments' => array(
            'content' => 'Under construction'),
    );
    // Page for manage bundles
    $items['managecollections'] = array(
        'title' => 'Manage Collections',
        'page callback' => 'flat_deposit_ui_view_info',
        'access callback' => TRUE,
        'page arguments' => array(
            'content' => 'Under construction'),
    );
    // Page for manage bundles
    $items['commitchanges'] = array(
        'title' => 'Commit changes',
        'page callback' => 'flat_deposit_ui_view_info',
        'access callback' => TRUE,
        'page arguments' => array(
            'content' => 'Under construction'),
    );

    return $items;
};

/**
 * @return string to be displayed on the page
 */
function flat_deposit_ui_view_info($variable)
{
    return t($variable);
}




/**
 * Implements hook_form().
 */
function flat_deposit_ui_admin_form($node, &$form_state)
{
    $form = array();

    $form['overview'] = array(
        '#markup' => t('This interface allows users to admin their deposit preferences'),
        '#prefix' => '<p>',
        '#suffix' => '</p>',
    );

    $form['enable_delete'] = array (
        '#title' => t('View only'),
        '#description' => t('Prevent yourself to accidentally delete data'),
        '#type' => 'checkbox',
        '#default_value' => 1,
        '#required' => TRUE,
    );

    $form['submit'] = array (
        '#type' => 'submit',
        '#value' => 'save',
    );

    return $form;
}


/**
 * Implements hook_block_info().
 */
function flat_deposit_ui_block_info()
{
    $blocks = array();

    $blocks['flat_deposit_menu'] = array(
        'info' => t('FLAT Deposit Main Menu'),
        'status' => TRUE,
        'region' => 'sidebar_second',
        'visibility' => BLOCK_VISIBILITY_NOTLISTED,
        'pages' => 'islandora/*',

    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function flat_deposit_ui_block_view($delta = '')
{
    if ($delta == 'flat_deposit_menu') {
        return array(
            'subject' => t('FLAT Deposit Main Menu'),
            'content' => flat_deposit_ui_menu_block_generate(),
        );

    }
}


// Implements flat deposit main menu block
function flat_deposit_ui_menu_block_generate(){
    // Build a render array.
    $output = array(
        'link_upload' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="/drupal/user/' . $GLOBALS['user']->uid  . '/imce" title="Upload data"><img title="Upload data" alt="Upload data" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Upload.png"/></a><br/>',
            '#suffix' => '<a href="/drupal/user/' . $GLOBALS['user']->uid  . '/imce">Upload data</a><br/></div>'),
        'link_view' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="view" title="View uploads"><img title="View uploads" alt="View uploads" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/View.png"/></a><br/>',
            '#suffix' => '<a href="view">View uploads</a><br/></div>'),
        'link_manage_bundles' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="managebundles/" title="Manage bundles"><img title="Manage bundles" alt="Manage bundles" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Manage.png"/></a><br/>',
            '#suffix' => '<a href="managebundles">Manage bundles</a><br/></div>'),
        'link_manage_collections' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="managecollections" title="Manage collections"><img title="Manage collections" alt="Manage collections" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Manage_coll.png"/></a><br/>',
            '#suffix' => '<a href="managecollections">Manage collections</a><br/></div>'),
        'link_commit' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="commitchanges" title="Commit changes"><img title="Commit changes" alt="Commit changes" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Commit.png"/></a><br/>',
            '#suffix' => '<a href="commitchanges">Commit changes</a><br/></div>'),
    );

    return $output;
}
//theme_menu_link()
?>
