<?php

function flat_test_mvd_permission()
{

    // setting up the right to use the deposit and to administer
    $permissions = array(
        'change fedora object xacml' => array(
            'title' => t('Change fedora object access policies'),
            'description' => t('Allows to change the xacml policies of a fedora object'),
        ),
    );
    return $permissions;
}

// Implements hook_menu().
function flat_test_mvd_menu() {
    $items['blok'] = array(
        'title' => 'Blok van Maurice',
        'type' => MENU_CALLBACK,
        'page callback' => 'show_islandora_object',
        'access arguments' => array(
            'access content',
        ),
    );
    $items['islandora/object/%islandora_object/object_pol'] = array(
        'title' => 'Change object access permissions',
        'type' => MENU_LOCAL_TASK,
        'weight' => 90,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('flat_test_mvd_xacml_editor_form', 2),
        'file' => 'inc/form_small.inc',
        'access callback' => 'islandora_object_access_callback',
        'access arguments' => array('change fedora object xacml', 2),
    );

    return $items;
}

function flat_test_mvd_islandora_object_access($op, $object, $user) {


    module_load_include('inc', 'islandora', 'includes/utilities');
    $has_access = FALSE; 
    switch ($op){
        case 'change fedora object xacml':

            $has_policy = $object['POLICY'];

            if ($has_policy){
                $has_access = TRUE;

            } else {
                $has_access = FALSE;

            }

            break;

        default:
           $has_access = NULL;
           break;

    }
    return $has_access;
}


function show_islandora_object(){


    $pid = 'lat:12345_8bca517b_29e9_4c85_a35a_6a616197db6a';
    $object = islandora_object_load($pid);

    $xml = $object->repository->api->m->getObjectXml($pid);

    $ds = islandora_datastream_load('POLICY', $pid);

    $output = '<div>My standard HTML content</div>';
    if ($ds){

        $output .= '<div>' . $ds->content. '</div>';

    }
    return $output;
}

function flat_test_mvd_block_info()
{
    $blocks = array();
    $blocks['block_voor_test'] = array(
        'info' => t('Dit is een view-test met block'),
        'status' => TRUE,
        'weight' => 0,
	'cache' => DRUPAL_NO_CACHE,
        'region' => 'content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => 'blok',
    );
    return $blocks;
}

/**
 * Implements hook_views_api().
 * register with views api
 * declare the path where to find the view include files
 * flat_test_mvd.views_default.inc
 */

function flat_test_mvd_views_api() {

  return array (
    'api' => '3.0',
    'path' => drupal_get_path('module', 'flat_test_mvd') . '/views',
  );
}