<?php
/**
 * Created by PhpStorm.
 * User: danrhe
 * Date: 07/11/16
 * Time: 16:22
 */

/**
 * Implements hook_menu().
 */
function flat_owncloud_menu()
{

    $items = array();

    // Admin configuration - Owncloud settings
    $items['admin/config/flat_deposit/manage_owncloud'] = array(
        'title' => 'Administer owncloud',
        'description' => 'Administer owncloud root path and credentials',
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'flat_owncloud_admin_form'),
        'file' => 'inc/flat_owncloud.admin_form.inc',
        'access arguments' => array('admin deposit module'));

    return $items;
}


/**
 * Show extra field 'mount_owncloud' in user profile form if owncloud is activated.
 * In case user activates owncloud integration (mount_owncloud ==TRUE) extra validation and submission handlers are added
 *
 */
function flat_owncloud_form_user_profile_form_alter(&$form, &$form_state, $form_id)
{
    $activated = variable_get('flat_owncloud', array())['activated'];

    if ($activated)

    {
        $form['#validate'][] = 'flat_owncloud_user_profile_owncloud_validate';
        $form['#submit'][] = 'flat_owncloud_user_profile_owncloud_submit';

    } else {

        hide($form['mount_owncloud']);

    }
}

/**
 * Implements hook_user_view().
 *
 * Hide mount setting if owncloud is not activated
 *
 *
 */
function flat_owncloud_user_view($account, $view_mode, $langcode){

    $activated = variable_get('flat_owncloud', array())['activated'];

       if (!$activated){

           $account->content['mount_owncloud']= NULL;

           unset($account->content['mount_owncloud']);

    }
}

/**
 * In case the value of mount_owncloud has changed, validate that data directory specified in drupal can be mounted in owncloud
 * Drupal user mounts will be unmounted and mounted again to see if this can be done. Result will be the outcome of the mounting process,
 * the mount, however will be removed in the end.
 */
function flat_owncloud_user_profile_owncloud_validate (&$form, &$form_state)
{
    $original_value = $form['mount_owncloud']['und']['#default_value'];
    $entered_value = $form_state['values']['mount_owncloud']['und'][0]['value'];

    // in case the value of mount_owncloud has changed
    if ($original_value != $entered_value AND $entered_value === "1") {

        module_load_include('inc', 'flat_owncloud', 'Helpers/owncloud_api');
        $oc = new OwnCloud();

        // Unmount first if owncloud is set to available and it is already available
        $oc->GetUserMount();
        if ($oc->mounted) {
            $oc->UnmountUserMount();
        }

        // initiate user directories if necessary
        module_load_include('inc', 'imce', 'inc/imce.page');
        global $user;
        imce_initiate_profile ($user, 'external');

        // Mount and Verify Drupal folder
        $oc->MountDataFolder();
        $oc->GetUserMount();
        $oc->VerifyMount();
        if (!$oc->verified) {
            form_set_error('owncloud_mount', 'Owncloud mount cannot be verified.');
            return $form;
        } else{
            $oc->UnmountUserMount();
        }
    }

    return $form;

}

/**
 * In case the value of mount_owncloud has changed, this submission handler either mounts or unmounts the user drupal data
 * directory mount
 */
function flat_owncloud_user_profile_owncloud_submit (&$form, &$form_state)
{
    $original_value = $form['mount_owncloud']['und']['#default_value'];
    $entered_value = $form_state['values']['mount_owncloud']['und'][0]['value'];

    module_load_include('inc', 'flat_owncloud', 'Helpers/owncloud_api');
    $oc = new OwnCloud();

    if ($original_value != $entered_value AND $entered_value === "1") {

        // Mount and Verify Drupal folder
        $oc->MountDataFolder();

        drupal_set_message('Owncloud can be used to upload data to archive');

    }  elseif ($original_value != $entered_value AND $entered_value === "0") {

        // Unmount first if owncloud is set to available and it is already available
        $oc->GetUserMount();

        if ($oc->mounted) {
            $oc->UnmountUserMount();
        }

        drupal_set_message('Owncloud integration has been deactivated');

    }
}


/**
 * Implements hook_node_insert().
 *
 * Updates the user file entries in owncloud database when a new node is created
 */
function flat_owncloud_node_insert($node)
{
    $activated = variable_get('flat_owncloud', array())['activated'];

    $user_data = user_load($node->uid);
    $mounted = $user_data->mount_owncloud['und']['0']['value'];

    if ($mounted AND $node->type == 'flat_bundle' AND $activated){
        module_load_include('inc', 'flat_owncloud', 'Helpers/owncloud_api');
        $oc = new OwnCloud();

        $oc->UpdateUserFiles();

    }

}
/**
 * update user file entries on owncloud database when a bundle is being viewed
 *
 */
function flat_owncloud_node_view_alter($node, $view_mode) {

    $activated = variable_get('flat_owncloud', array())['activated'];

    $account = user_load($node['#node']->uid);
    $field_items = field_get_items('user', $account, 'mount_owncloud');
    if ($field_items) {

        if ($field_items[0]['value'] AND $node['#bundle'] == 'flat_bundle' AND $node['#view_mode'] == 'full' AND $activated) {
            module_load_include('inc', 'flat_owncloud', 'Helpers/owncloud_api');
            $oc = new OwnCloud();

            $oc->UpdateUserFiles();

        }
    }
}


/**
 * Implements hook_node_delete().
 * update user file entries on owncloud database when a bundle is being deleted
 */
function flat_owncloud_node_delete($node)
{
    $activated = variable_get('flat_owncloud', array())['activated'];

    $user_data = user_load($node->uid);
    $mounted = $user_data->mount_owncloud['und']['0']['value'];

    if ($mounted AND $node->type == 'flat_bundle' AND $activated){
        module_load_include('inc', 'flat_owncloud', 'Helpers/owncloud_api');
        $oc = new OwnCloud();

        $oc->UpdateUserFiles();

    }

}