<?php
/**
 * @file
 * Custom user interface for the FLAT data repository
 */


/*
 *  Load Dependencies
 */
require_once ('fedora_queries.php');
// require_once ('drupal_queries.php');
// require_once ('misc.php');


module_load_include('inc', 'flat_deposit_ui', 'Helpers/owncloud_api');

/*
 * Variable and constant definitions
 */

if ($GLOBALS['user']->uid){
    define('USER', $GLOBALS['user']->name);

    define('FREEZE_DIR', variable_get('flat_deposit_paths',array())['freeze']);
    define('TEMP_DIR', variable_get('flat_deposit_paths',array())['temp']);
    define('BAG_DIR', variable_get('flat_deposit_paths',array())['bag']);
    define('WEB_SERVER', variable_get('flat_deposit_paths',array())['webserver']);

    define('USER_FREEZE_DIR', FREEZE_DIR . USER);
    define('USER_DRUPAL_DATA_DIR', 'public://users/' . USER );
}

/**
 * Implements hook_help().
 * @param $path
 * @return string
 */

function flat_deposit_ui_help($path, $args){
    switch ($path){
        case 'admin/help#flat_deposit_ui':{
            $ret_val = '<h3>' . t('About') . '</h3>';
            $ret_val .= '<p>' . t('The FLAT deposit UI module is designed to manage the project data of each institutes employee') . '</p>';
            return $ret_val;
            break;
        }
    }

}

/**
 * Implements hook_permission().
 */
function flat_deposit_ui_permission()
{
    return array(
        'admin deposit module' => array(
            'title' => t('Administration of the deposit module'),
            'description' => t('All administrative tasks'),
            'restrict access' => TRUE),
        'use deposit module' => array(
            'title' => t('Usage of the deposit module'),
            'description' => t('Upload data to the FLAT deposit')));
}


/**
 * Implements hook_menu().
 */
function flat_deposit_ui_menu()
{
    $access=array('admin deposit module');

    $items = array();

    // Admin configuration group
    $items['admin/config/flat_deposit_ui'] = array(
        'title' => 'FLAT deposit UI',
        'description' => 'Administer FLAT deposit user interface',
        'access callback' => TRUE);

    // Admin configuration - Upload settings
    $items['admin/config/flat_deposit_ui/customize'] = array(
        'title' => 'Customize deposit settings',
        'description' => 'Administer FLAT deposit settings such as temporal storage folders and used plugins',
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'flat_deposit_ui_admin_form'),
        'access arguments' => $access);

    // Admin configuration - Owncloud settings
    $items['admin/config/flat_deposit_ui/manage_owncloud'] = array(
        'title' => 'Administer owncloud',
        'description' => 'Administer owncloud root path and credentials',
        'page callback' => 'drupal_get_form',
        'page arguments' => array( 'flat_deposit_ui_owncloud_form'),
        'access arguments' => $access);

    // Page for uploading data
    $items['workspace'] = array(
        'title' => 'Workspace',
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('flat_deposit_ui_workspace_form'),
        'access arguments' => array('use deposit module'));

    // Page for ingested data
    $items['view'] = array(
        'title' => 'View archived data',
        'description' => 'Notification of data ingested to server',
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'flat_deposit_ui_view_ingested_files',
        'access arguments' => array('use deposit module'));

    // Page for manage bundles
    $items['managebundles'] = array(
        'title' => 'Manage bundles',
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'flat_deposit_ui_manage_bundles',
        'page arguments' => array(
            'content' => 'Under construction'),
        'access arguments' => array('use deposit module'));

    // Page for manage collections
    $items['managecollections'] = array(
        'title' => 'Manage Collections',
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'flat_deposit_ui_view_collections',
        'page arguments' => array(
            'content' => 'Under construction'),
        'access arguments' => array('use deposit module'));

    // Page for commiting changes
    $items['commitchanges'] = array(
        'title' => 'Commit changes',
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('flat_deposit_ui_commit_form'),
        'access arguments' => array('use deposit module'));

    return $items;
};


/**
 * Implements hook_form().
 */
function flat_deposit_ui_admin_form($node, &$form_state)
{
    $form = array();

    $form['overview'] = array(
        '#markup' => t('This interface allows administrators to customize the deposit\'s settings'),
        '#prefix' => '<p>',
        '#suffix' => '</p>',);

    $form['paths'] = array(
        '#type' => 'fieldset',
        '#title' => t('Paths'));

    $form['paths']['freeze'] = array (
        '#type' => 'textfield',
        '#title' => 'Freeze',
        '#description' => t('Absolute path of the location where frozen data will be stored'),
        '#default_value' => FREEZE_DIR,
        '#required' => TRUE,);

    $form['paths']['temp'] = array (
        '#type' => 'textfield',
        '#title' => 'Temporary',
        '#description' => t('Absolute path of the location where the user data will temporarily be stored for ingestion'),
        '#default_value' => TEMP_DIR,
        '#required' => TRUE,);

    $form['paths']['bags'] = array (
        '#type' => 'textfield',
        '#title' => 'Bags',
        '#description' => t('Absolute path of the location where Fedora can needs to search for complete SIP\'s that will be ingested'),
        '#default_value' => BAG_DIR,
        '#required' => TRUE,);

    $form['paths']['webserver'] = array (
        '#type' => 'textfield',
        '#title' => 'Webserver',
        '#description' => t('Name of the webserver (e.g. www-data)'),
        '#default_value' => WEB_SERVER,
        '#required' => TRUE,);

    $form['modules'] = array(
        '#type' => 'fieldset',
        '#title' => t('Modules'));

    $form['modules']['owncloud'] = array (
        '#title' => t('Owncloud'),
        '#description' => t('Incorporate owncloud into module'),
        '#type' => 'checkbox',
        '#default_value' => variable_get('flat_deposit_modules',array())['owncloud'],);

    $form['submit'] = array (
        '#type' => 'submit',
        '#value' => t('Save'));

    $form['restore'] = array (
        '#type' => 'submit',
        '#value' => t('Reset to defaults'),
        '#submit' => array('flat_deposit_ui_admin_form_reset_submit'));

    return $form;
}

function flat_deposit_ui_admin_form_submit ($form, &$form_state)
{
    variable_set('flat_deposit_paths', array(
        'freeze' => $form_state['values']['freeze'],
        'temp' => $form_state['values']['temp'],
        'bag'=> $form_state['values']['bags'],
        'webserver'=> $form_state['values']['webserver']));

    variable_set('flat_deposit_modules', array(
        'owncloud' =>$form_state['values']['owncloud']));

    drupal_set_message(t('Changed values have been saved'));
}

function flat_deposit_ui_admin_form_reset_submit ($form, &$form_state){
    module_load_include('inc', 'flat_deposit_ui', 'inc/flat_deposit_ui_core_settings');
    flat_deposit_set_paths();
    flat_deposit_set_modules();
    flat_deposit_set_owncloud();
    drupal_set_message(t('All settings have been reset to default'));
}


/**
 * Implements hook_form().
 */
function flat_deposit_ui_owncloud_form($node, &$form_state)
{
    $form = array();

    $form['overview'] = array(
        '#markup' => t('Administrators can configure here owncloud settings. It is required that owncloud runs on the same server as this drupal installation'),
        '#prefix' => '<p>',
        '#suffix' => '</p>',);

    $form['settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Owncloud settings'));

    $form['settings']['admin_name'] = array (
        '#type' => 'textfield',
        '#title' => 'Owncloud admin name',
        '#description' => t('The owncloud admin user name'),
        '#default_value' => variable_get('owncloud_settings',array())['admin_name'],
        '#required' => TRUE,);

    $form['settings']['admin_pass'] = array (
        '#type' => 'textfield',
        '#title' => 'Owncloud admin password',
        '#description' => t('The owncloud admin user password'),
        '#default_value' => variable_get('owncloud_settings',array())['admin_pass'],
        '#required' => TRUE,);

    $form['settings']['root_dir'] = array (
        '#type' => 'textfield',
        '#title' => 'Owncloud root directory',
        '#description' => t('The owncloud installation path'),
        '#default_value' => variable_get('owncloud_settings',array())['root_dir'],
        '#required' => TRUE,);

    $form['submit'] = array (
        '#type' => 'submit',
        '#value' => t('Save'));

    $form['restore'] = array (
        '#type' => 'submit',
        '#value' => t('Reset to defaults'),
        '#submit' => array('flat_deposit_ui_admin_form_reset_submit'));

    return $form;
}


function flat_deposit_ui_owncloud_form_submit ($form, &$form_state)
{
    variable_set('owncloud_settings', array(
        'admin_name' => $form_state['values']['admin_name'],
        'admin_pass' => $form_state['values']['admin_pass'],
        'root_dir'=> $form_state['values']['root_dir']));

    drupal_set_message(t('Changed values have been saved'));
}

function flat_deposit_ui_owncloud_form_reset_submit ($form, &$form_state){
    module_load_include('inc', 'flat_deposit_ui', 'inc/flat_deposit_ui_core_settings');
    flat_deposit_set_owncloud();
    drupal_set_message(t('Owncloud settings have been reset to default'));
}


/**
 * Implements hook_block_info().
 */
function flat_deposit_ui_block_info()
{
    $blocks = array();

    $blocks['flat_deposit_menu'] = array(
        'info' => t('FLAT Deposit Main Menu'),
        'status' => TRUE,
        'region' => 'sidebar_second',
        'visibility' => BLOCK_VISIBILITY_NOTLISTED,
        'pages' => 'islandora/*',

    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function flat_deposit_ui_block_view($delta = '')
{
    if ($delta == 'flat_deposit_menu') {
        return array(
            'subject' => t('FLAT Deposit Main Menu'),
            'content' => flat_deposit_ui_menu_block_generate(),
        );

    }
}

// Implements flat deposit main menu block
function flat_deposit_ui_menu_block_generate(){
    // Build a render array.

    $output = array(
        'link_workspace' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="/drupal/workspace" title="My Workspace"><img title="My Workspace" alt="My Workspace" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Upload.png"/></a><br/>',
            '#suffix' => '<a href="/drupal/workspace">My Workspace</a><br/></div>'),
        'link_view' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="/drupal/view" title="View uploads"><img title="View uploads" alt="View uploads" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/View.png"/></a><br/>',
            '#suffix' => '<a href="/drupal/view">View uploads</a><br/></div>'),
        'link_manage_bundles' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="/drupal/managebundles/" title="Manage bundles"><img title="Manage bundles" alt="Manage bundles" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Manage.png"/></a><br/>',
            '#suffix' => '<a href="/drupal/managebundles">Manage bundles</a><br/></div>'),
        'link_manage_collections' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="/drupal/managecollections" title="Manage collections"><img title="Manage collections" alt="Manage collections" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Manage_coll.png"/></a><br/>',
            '#suffix' => '<a href="/drupal/managecollections">Manage collections</a><br/></div>'),
        'link_commit' => array(
            '#type' => 'markup',
            '#prefix' => '<div>',
            '#markup' => '<a href="/drupal/commitchanges" title="Commit changes"><img title="Commit changes" alt="Commit changes" src="/drupal/'.drupal_get_path('module','flat_deposit_ui').'/Images/Commit.png"/></a><br/>',
            '#suffix' => '<a href="/drupal/commitchanges">Commit changes</a><br/></div>'),
    );
    return $output;
}


/**
 * Implements hook_form
 * @return string to be displayed on the page
 */
function flat_deposit_ui_workspace_form($form, &$form_state)
{

    // initiate user directories if necessary
    module_load_include('inc', 'imce', 'inc/imce.page');
    global $user;
    imce_initiate_profile ($user);

    #$my_code = 'window.open(\'imce\', \'windowName\', \'width=640, height=480\');';

    // Define the workspace form
    $form['field_1'] = array(
        '#type' => 'fieldset',
        '#title' => t('Create bundles'),
        '#description' => t('Here you can create new bundles. Keep in mind that new bundles need to have unique names.'));

    $form ['field_1'] ['bundle_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name of bundle'));

    $form ['field_1'] ['collection_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Belongs to collection'));

    $form ['field_1']['init_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Click to create new workspace bundle'),
        '#submit' => array('flat_deposit_ui_workspace_bundle_init_submit'),
        '#validate' => array('flat_deposit_ui_workspace_bundle_init_validate'));


    $open_bundles = array_diff(scandir(USER_DRUPAL_DATA_DIR), array('..', '.'));
    $list_open_bundles = theme('item_list', array('items' => $open_bundles,
                                                    'title' => '',
                                                    'type' => 'ul',
                                                    'attributes' => array()));

    $form['field_2'] = array(
        '#type' => 'fieldset',
        '#title' => t('Open bundles'),
        '#description' => $list_open_bundles );

    $form['field_2']['upload_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Upload or browse data'),
        '#submit' => array('flat_deposit_ui_workspace_upload_submit'),);

    $form['field_3'] = array(
        '#type' => 'fieldset',
        '#title' => t('Other tasks'),
        );

    $form['field_3']['sync'] = array(
        '#type' => 'submit',
        '#value' => t('Sync owncloud'),
        '#description' => t('Owncloud needs to be synced with this workspace if data (other than metadata) is uploaded using the workspace explorer'),
        '#submit' => array('flat_deposit_ui_workspace_sync_submit'),);

    // Check for integrity with owncloud in case this features is selected
    $oc = new OwnCloud();
    if ($oc->ok){
        return $form;
    }
}

/**
 * Workspace form which allows to create new projects or browse data in file explorer
 * @param $form
 * @param $form_state
 */

function flat_deposit_ui_workspace_bundle_init_validate(&$form, &$form_state)
{
    $bundle_name = $form_state['values']['bundle_name'];

    $message = FALSE;

    $form_state['full_directory_path'] = USER_DRUPAL_DATA_DIR . '/' .  $bundle_name;

    //Check that the input values are of the proper format
    if (!preg_match('/^[a-zA-Z0-9\_]{2,40}+$/', $bundle_name)) {
        $message = 'Allowed are all letters, numbers and underscores (max length 40)';}

    //Check that bundle name is distinctive from existing bundles
    else{
        $dirs = scandir(USER_DRUPAL_DATA_DIR);
        if (file_exists(USER_FREEZE_DIR)){ $dirs = array_merge($dirs, array_diff(scandir(USER_FREEZE_DIR), array('..', '.')));}

        foreach ($dirs as $dir){
            if (strtolower($dir)==strtolower($bundle_name)){$message = "Bundle with same or very similar bundle name exists";}
        };
    };
    //redirect to form in case error message is created
    if ($message) {form_set_error ('bundle_name', $message);}
}

/**
 * creates a new local folders on click
 */
function flat_deposit_ui_workspace_bundle_init_submit(&$form, &$form_state)
{
    drupal_set_message(t('Creating new upload folders'));

    $target = $form_state['full_directory_path'];
    drupal_mkdir($target);
    drupal_chmod($target, 0775);
    drupal_mkdir($target . '/metadata');
    drupal_mkdir($target . '/data');


    //create symbolic link in owncloud user directory and refresh to see new directory
    $oc = new OwnCloud();
    $bundle = $form_state['values']['bundle_name'];
    $oc->CreateLinkAndSync($target, $bundle);

    $collection = $form_state['values']['collection_name'];

    //Make entry on database (if not exists)
    module_load_include('inc', 'flat_deposit_ui' , '/inc/config');
    $config = get_initial_bundle_profile();
    $config['user_id'] = USER;
    $config['bundle'] = $bundle;
    $config['collection'] = $collection;
    $config['status'] = 'open';

    $result = db_select('flat_deposit_ui_upload_log', 'bundle')
        ->fields('bundle', array('bundle'))
        ->condition('user_id', USER)
        ->condition('bundle', $bundle)
        ->condition('collection', $collection)
        ->execute()
        ->rowCount();

    if ($result) {
        db_update('flat_deposit_ui_upload_log')
            ->fields(array('status' => 'open'))
            ->condition('user_id', USER)
            ->condition('bundle', $bundle)
            ->condition('collection', $collection)
            ->execute();
    } else {
        drupal_write_record('flat_deposit_ui_upload_log', $config);
    }
}

#
/**
 * $manage_bundles_form_submit
 */

function flat_deposit_ui_workspace_upload_submit(&$form, &$form_state)
{
    drupal_set_message(t('Do your uploads'));

    $options=array();
    $options['absolute'] = TRUE;

    $form_state ['redirect'] = 'user/' . $GLOBALS['user']->uid  . '/imce';
}


function flat_deposit_ui_workspace_sync_submit(&$form, &$form_state)
{
    $oc = new OwnCloud();
    $oc->UpdateUserFiles();
    drupal_set_message(t('Owncloud has been synced'));


}

/**
 * Gets a list of all data ingested
 */
function flat_deposit_ui_view_ingested_files() {

    $tuque = islandora_get_tuque_connection();

    $query = create_query_all_owned_files(USER);

    $results = $tuque->repository->ri->sparqlQuery($query);

    $rows = array();
    foreach ($results as $result) {
        $pid = $result['pid']['value'];
        $label = $result['label']['value'];
        $createdDate = $result['created']['value'];

        $createdDate_formatted = format_date(strtotime($createdDate));

        $var = array(
            'theme' => 'link',
            'text' => 'click here',
            'path' => "islandora/object/$pid",
            'options' => array(
                'attributes' => array(),
                'html' => FALSE
            )
        );
        $link = theme_link($var);

        $row = array($label, $createdDate_formatted, $link) ;
        array_push($rows,$row);
    }

    // creating header array
    $header = array( t('File name'), t('Date ingested'),t('Direct link'));

    $output = array(
        // Table, using the theme hook 'table'.
        'notification' => array(
            '#theme' => 'table',
            '#caption' => t('Notification'),
            '#header' => $header,
            '#rows' => $rows,
        ),
    );

    return $output;
}


/**
 * Gets a list of all data ingested
 */
function flat_deposit_ui_view_collections()
{
    $tuque = islandora_get_tuque_connection();

    $query = query_owned_collections(USER);

    $results = $tuque->repository->ri->sparqlQuery($query);

    $rows = array();

    foreach ($results as $result) {
        $pid = $result['pid']['value'];
        $label = $result['label']['value'];
        $createdDate = $result['created']['value'];

        $createdDate_formatted = format_date(strtotime($createdDate));

        $tmp = array(
            'theme' => 'link',
            'text' => 'click here',
            'path' => "islandora/object/$pid",
            'options' => array(
                'attributes' => array(),
                'html' => FALSE
            )
        );
        $link = theme_link($tmp);

        $row = array($label, $createdDate_formatted, $link) ;
        array_push($rows,$row);
    }

    // creating header array
    $header = array( t('Name'), t('Date ingested'),t('Direct link'));
    #islandora_object_load($object_id)
    $output = array(
        // Table, using the theme hook 'table'.
        'notification' => array(
            '#theme' => 'table',
            '#caption' => t('Projects'),
            '#header' => $header,
            '#rows' => $rows,
        ),
    );

    return $output;
}

/**
 * Gets a list of all data ingested
 */
function flat_deposit_ui_manage_bundles()
{
    $tuque = islandora_get_tuque_connection();

    $query = query_owned_collections(USER);

    $results = $tuque->repository->ri->sparqlQuery($query);

    // convert results to table format
    $header = array( t('PID'));
    $rows = array();

    foreach ($results as $result) {
        $pid = $result['pid']['value'];
        $row = array($pid) ;
        array_push($rows,$row);
    }


    $query2 = query_owned_collections('');

    $results2 = $tuque->repository->ri->sparqlQuery($query2);

    // convert results to table format
    $rows2 = array();
    foreach ($results2 as $result2) {
        $pid = $result2['pid']['value'];
        $row = array($pid) ;
        array_push($rows2,$row);
    }


    $output = array(
        // Table, using the theme hook 'table'.
        'output sparql query' => array(
            '#theme' => 'table',
            '#caption' => t('Objects owned by ""'),
            '#header' => $header,
            '#rows' => $rows,
        ),
        // Table, using the theme hook 'table'.
        'output api_a' => array(
            '#theme' => 'table',
            '#caption' => t('Objects owned by ' . USER),
            '#header' => $header,
            '#rows' => $rows2,
        ),
    );
    return $output;
}


/**
 * Presents all user entries that are found in the log table and allows to further process them
 */
function flat_deposit_ui_commit_form($form, $form_state)
{
    $results = db_select('flat_deposit_ui_upload_log','p')
        ->fields('p',array('user_id', 'bundle', 'collection', 'status', 'exceptions', 'date_bundle_ingest'))
        ->condition('user_id', 'admin')
        ->orderBy('collection')
        ->orderBy('bundle')
        ->execute();

    $open_bundles = array();
    $frozen_bundles = array();
    $archived_bundles = array();
    $other_bundles = array();

    // make array of open / frozen bundles in order to use these in a form
    foreach ($results as $entry) {
        $array_entry = json_decode(json_encode($entry), true);
        if ($array_entry['status'] == 'open' && file_exists(USER_DRUPAL_DATA_DIR . '/' . $array_entry['bundle'])) {
            $open_bundles [] = $array_entry;
        } elseif ($array_entry['status'] == 'archived' ) {
            $archived_bundles [] = $array_entry;
        } elseif (file_exists(USER_FREEZE_DIR . '/' . $array_entry['bundle'])) {
            $frozen_bundles [] = $array_entry;
        } else {
            $other_bundles [] = $array_entry;
        }
    }


    // make form with three fields : 1) open bundles, 2) frozen bundles 3) additional (admin) tasks
    $form = array();

    //   open bundles field
    $form['open_bundles'] = array(
        '#type' => 'fieldset',
        '#title' => t('Open bundles'),);

    $header = array(
        'collection' => t('Collection Name'),
        'bundle' => t('Bundle Name'),
        'status' => t('Status'),
        'exceptions' => t('Exception'),
    );
    $options = array();

    foreach ($open_bundles as $key => $bundle) {
        $options[$key] = array(
            'collection' => $bundle['collection'],
            'bundle' => $bundle['bundle'],
            'status' => $bundle['status'],
            'exceptions' => $bundle['exceptions'],
        );
    }

    $form['open_bundles']['table_open_bundles'] = array (
        '#type' => 'tableselect',
        '#header' => $header,
        '#options' => $options,
    );

    $form['open_bundles']['actions']['freeze'] = array(
        '#type' => 'submit',
        '#value' => t('Freeze bundle'),
        '#submit' => array('flat_deposit_ui_commit_form_freeze_submit'),
        '#validate' => array('flat_deposit_ui_commit_form_freeze_validate'),);

    $form['open_bundles']['actions']['delete'] = array(
        '#type' => 'submit',
        '#value' => t('Delete bundle'),
        '#submit' => array('flat_deposit_ui_commit_form_delete_submit'));


    $form['open_bundles'] ['data_open_bundles']= array(
        '#type' => 'value',
        '#value' => $open_bundles);

    // frozen bundles#
    $form['frozen_bundles'] = array(
        '#type' => 'fieldset',
        '#title' => t('Bundles ready to be archived'),);

    $header = array(
        'collection' => t('Collection Name'),
        'bundle' => t('Bundle Name'),
        'status' => t('Status'),
        'exceptions' => t('Exception'),
    );
    $options = array();

    foreach ($frozen_bundles as $key => $bundle) {
        $options[$key] = array(
            'collection' => $bundle['collection'],
            'bundle' => $bundle['bundle'],
            'status' => $bundle['status'],
            'exceptions' => $bundle['exceptions'],
        );
    }

    $form['frozen_bundles']['table_frozen_bundles'] = array (
        '#type' => 'tableselect',
        '#header' => $header,
        '#options' => $options,
    );

    // Allow actions for frozen data: ingest or open up for changes
    $form['frozen_bundles']['actions']['unfreeze'] = array(
        '#type' => 'submit',
        '#value' => t('Unfreeze bundle'),
        '#submit' => array('flat_deposit_ui_commit_form_unfreeze_submit'),
        '#validate' => array('flat_deposit_ui_commit_form_unfreeze_validate'),);

    $form['frozen_bundles']['actions']['ingest'] = array(
        '#type' => 'submit',
        '#value' => t('Upload project to database'),
        '#submit' => array('flat_deposit_ui_commit_form_ingest_serve_submit'),
        '#validate' => array('flat_deposit_ui_commit_form_ingest_serve_validate'),);

    $form['frozen_bundles']['data_frozen_bundles'] = array(
        '#type' => 'value',
        '#value' => $frozen_bundles);

    # Ingested #
    $form['archived_bundles'] = array(
        '#type' => 'fieldset',
        '#title' => t('Bundles on database'),
    );

    $header = array(
        'collection' => t('Collection Name'),
        'bundle' => t('Bundle Name'),
        'status' => t('Status'),
        'date' => t('Bundle archived on'),
    );

    foreach ($archived_bundles as $key => $bundle) {
        $options[$key] = array(
            'collection' => $bundle['collection'],
            'bundle' => $bundle['bundle'],
            'status' => $bundle['status'],
            'date' => format_date($bundle['date_bundle_ingest'])
        );
    }

    $form['archived_bundles']['table_archived_bundles'] = array (
        '#type' => 'tableselect',
        '#header' => $header,
        '#options' => $options,
    );



    # other #
    $form['other'] = array(
        '#type' => 'fieldset',
        '#title' => t('Other tasks'),
    );
    // Add extra buttons for other tasks
    $form['other']['buttons']['refresh'] = array(
        '#type' => 'submit',
        '#value' => 'Refresh archived bundles',
        '#description' => 'Reinventarize bundles in archive',
        '#submit' => array('flat_deposit_ui_commit_form_refresh_archived_submit'),
    );


    return $form;
}


/**
 * Performs general checks as accessibility of the user freeze directory by the webserver, and bundle-wise sanity checks
 * @param $form
 * @param $form_state
 * @return mixed
 */
function flat_deposit_ui_commit_form_freeze_validate (&$form, &$form_state)
{

    // Check if freeze directory exists
    if (!file_exists(FREEZE_DIR)) {
        form_set_error ('freeze_error', "No freeze directory exists. Please contact administator");
        return $form;
    }

    // Check if freeze directory is owned by web-Server and writable
    $owner = posix_getpwuid(fileowner(FREEZE_DIR));
    if ($owner['name'] != WEB_SERVER) {
        form_set_error ('freeze_error', "Freeze directory is not writable by application. Please contact administator");
        return $form;
    }

    // Check if user backend directory exists or can be created
    if (!file_exists(USER_FREEZE_DIR)) {
        $created = drupal_mkdir(USER_FREEZE_DIR, NULL, true);
        if (!$created) {
            form_set_error('freeze_error', "Could not create user backend directory. Please contact administator");
            return $form;
        }
    }

    // Sanity checks for each checked checkbox
    foreach ($form_state['values']['table_open_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_open_bundles'][$key]['bundle'];
            $frozen_bundle_dir = FREEZE_DIR . '/' . USER . '/' . $bundle;

            // Check if bundle directory on backend already exists
            if (file_exists($frozen_bundle_dir)) {
                form_set_error ('freeze_error', 'A bundle with the name ' . $bundle . ' has already been frozen.');
                return $form;
            }

            // Check if upload contains at least one cmdi file
            if (count(glob(drupal_realpath(USER_DRUPAL_DATA_DIR . '/' . $bundle . '/metadata/*.cmdi'))) == 0) {
                form_set_error('freeze_error', "No meta data available for upload bundle. Please provide a .cmdi file");
                return $form;
            }

            // Checks on cmdi file
            $cmdi = glob(drupal_realpath(USER_DRUPAL_DATA_DIR) . '/' . $bundle . '/metadata/*cmdi')[0];

            $finfo = new finfo(FILEINFO_MIME, "/usr/share/misc/magic");
            $mime = $finfo->file($cmdi);


            // Is cmdi a valid xml file?
            if (!strpos($mime, "/plain")) {
                form_set_error('freeze_error', "cmdi file is no valid xml file");
                return $form;}

            if (!simplexml_load_file($cmdi)) {
                form_set_error('freeze_error', "cmdi file is no valid xml file");
                return $form;}

            // Check if bundle name match up with bundle name as found in cmdi-file
            $content = json_decode(json_encode((array)simplexml_load_file($cmdi)), TRUE);
            if ($content['Components']['lat-session']['Name'] != $bundle){
                form_set_error('freeze_error', "cmdi file and bundle directory don't match. Please rename bundle");
                return $form;}

        }
    }
    return $form;
}



function flat_deposit_ui_commit_form_freeze_submit ($form, &$form_state)
{
    foreach ($form_state['values']['table_open_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_open_bundles'][$key]['bundle'];
            $collection = $form_state['values']['data_open_bundles'][$key]['collection'];
            $source = drupal_realpath(USER_DRUPAL_DATA_DIR . '/' . $bundle);
            $destination = USER_FREEZE_DIR . '/' . $bundle;
            $moved = rename($source, $destination);

            if ($moved) {
                // update database entry
                db_update('flat_deposit_ui_upload_log')
                    ->fields(array(
                        'freeze_time' => (int) $_SERVER['REQUEST_TIME'],
                        'exceptions' => '',
                        'status' => 'awaiting'))
                    ->condition('user_id', USER)
                    ->condition('bundle', $bundle)
                    ->condition('bundle', $collection)
                    ->condition('status', 'open')
                    ->execute();

                //remove symbolic link in owncloud user directory
                $oc = new OwnCloud();
                $oc->DeleteLinkAndSync($bundle);
                drupal_set_message(t('Project ' . $bundle . ' is frozen'));
            }
        }
    }
}

function flat_deposit_ui_commit_form_delete_submit($form, &$form_state)
{
    foreach ($form_state['values']['table_open_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_open_bundles'][$key]['bundle'];
            $collection = $form_state['values']['data_open_bundles'][$key]['collection'];
            $source = USER_DRUPAL_DATA_DIR . '/' . $bundle;
            $del = file_unmanaged_delete_recursive($source);

            //#unlink owncloud symlink
            $oc = new OwnCloud();
            $oc->DeleteLinkAndSync($bundle);

            // Remove entry from flat_deposit_ui_upload_log

            $results = db_delete('flat_deposit_ui_upload_log')
                ->condition('user_id', USER)
                ->condition('bundle', $bundle)
                ->condition('collection', $collection)
                ->condition('status', 'open')
                ->execute();


            if ($del) {
                $message = t('Bundle ' . $bundle . ' has been deleted.');
            } else {
                $message = t('Bundle ' . $bundle . ' has not been deleted.');
            }

            if ($results) {
                $message .= t(' Database has been updated');
            } else {
                $message .= t(' Note: Database has not been updated');
            }
            drupal_set_message($message);

        }
    }
}



function flat_deposit_ui_commit_form_unfreeze_validate (&$form, &$form_state)
{

    $message = FALSE;

    // Check if user drupal data directory exists
    if (!file_exists(USER_DRUPAL_DATA_DIR)) {
        form_set_error ('unfreeze_error', "User Drupal data directory does not exist. Please contact administator");
        return $form;
    }

    // Check if backend is owned by www-data and writable
    $owner = posix_getpwuid(fileowner(USER_DRUPAL_DATA_DIR));
    if ($owner['name'] != WEB_SERVER) {
        form_set_error ('unfreeze_error', "User Drupal data directory is not writable by application. Please contact administrator");
        return $form;
    }

    // Check if drupal data bundle directory already exists
    // for each checked box
    foreach ($form_state['values']['table_open_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_open_bundles'][$key]['bundle'];

            $open_bundle_dir = USER_DRUPAL_DATA_DIR . '/' . $bundle ;
            if (file_exists($open_bundle_dir)) {
                if (!$message) $message = "";
                $message .= 'A bundle with the name ' . $bundle . ' has already been frozen.';}
        }
    }

    //redirect to form in case error message is created
    if ($message) {
        form_set_error ('unfreeze_error', $message);
    }

    return $form;
}


function flat_deposit_ui_commit_form_unfreeze_submit ($form, &$form_state)
{
    foreach ($form_state['values']['table_frozen_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_frozen_bundles'][$key]['bundle'];
            $collection = $form_state['values']['data_frozen_bundles'][$key]['collection'];
            $source = USER_FREEZE_DIR . '/' . $bundle;
            $destination = drupal_realpath(USER_DRUPAL_DATA_DIR . '/' . $bundle);
            $moved = rename($source, $destination);


            if ($moved) {
                // update database entry
                db_update('flat_deposit_ui_upload_log')
                    ->fields(array(
                        'status' => 'open',
                        'freeze_time' => 0))
                    ->condition('user_id', USER)
                    ->condition('bundle', $bundle)
                    ->condition('collection', $collection)
                    ->execute();


                //add symbolic link to owncloud user directory
                $oc = new OwnCloud();
                $oc->CreateLinkAndSync($destination, $bundle);

                drupal_set_message(t('Bundle ' . $bundle . ' is open and can be changed'));
            }
        }
    }
}


/**
 * Doesn't do anything at the moment. Extend with further validation if needed
 * @param drupal form $form
 * @param drupal form state $form_state
 * @return form
 */

function flat_deposit_ui_commit_form_ingest_serve_validate (&$form, &$form_state)
{

    foreach ($form_state['values']['table_frozen_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_frozen_bundles'][$key]['bundle'];
            $collection = $form_state['values']['data_frozen_bundles'][$key]['collection'];

            $result = db_select('flat_deposit_ui_upload_log', 'bundle')
                ->fields('bundle', array('bundle'))
                ->condition('user_id', USER)
                ->condition('bundle', $bundle)
                ->condition('collection', $collection)
                ->condition('status', 'awaiting')
                ->execute()
                ->rowCount();
            if (!$result){
                $message = 'Incorrect status. Bundle is either already in process or needs revision';
                form_set_error ('ingest_error', t($message));
            }

        }
    }

    return $form;
}


/**
 * Updates upload_log table and triggers a service that ingests specified bundles into the archive
 *
 * @param $form
 * @param $form_state
 *
 */

function flat_deposit_ui_commit_form_ingest_serve_submit ($form, &$form_state)
{

    foreach ($form_state['values']['table_frozen_bundles'] as $key => $checked) {
        if (!is_int($checked)) {

            // extract bundle name from form data
            $bundle = $form_state['values']['data_frozen_bundles'][$key]['bundle'];
            $collection = $form_state['values']['data_frozen_bundles'][$key]['collection'];
            db_update('flat_deposit_ui_upload_log')
                ->fields(array('status' => 'awaiting'))
                ->condition('user_id', USER)
                ->condition('bundle', $bundle)
                ->condition('collection', $collection)
                ->execute();


            $data_to_post = array();
            #$data_to_post['module_path'] = httprl_build_url_self(drupal_get_path('module', 'flat_deposit_ui')); //doesn't work at the moment but should be used
            $data_to_post['module_path'] = '/var/www/html/drupal/sites/all/modules/custom/flat_deposit_ui/';
            $data_to_post['app_path'] = '/app/flat/';
            $data_to_post['freeze_dir'] = FREEZE_DIR;
            $data_to_post['bag_dir'] = BAG_DIR;
            $data_to_post['web-server'] = WEB_SERVER;
            $data_to_post['bag_exe'] = '/usr/local/bin/bagit-4.9.0/bin/bag';
            $data_to_post['fedora_home'] = '/var/www/fedora';
            $data_to_post['user_id'] = USER;
            $data_to_post['bundle'] = $bundle;
            $data_to_post['collection'] = $collection;

            $options = array(
                'method' => 'POST',
                'data' => $data_to_post,
                'blocking' => FALSE,
                'headers' => array(
                    // Set the Host header to self.
                    'Host' => $_SERVER['HTTP_HOST'],),
            );

            $url = httprl_build_url_self(drupal_get_path('module', 'flat_deposit_ui') . "/Helpers/Ingest_service.php");

            httprl_request($url, $options);

            // Execute request.
            $request = httprl_send_request();



/*
            $url_debug = 'http://192.168.99.100/drupal/' . drupal_get_path('module', 'flat_deposit_ui') . "/Helpers/Ingest_service.php";
            $ch = curl_init();
            curl_setopt_array($ch, array(

                CURLOPT_URL => $url_debug,
                CURLOPT_COOKIE => "XDEBUG_SESSION=PHPSTORM",
                CURLOPT_POST => sizeof($data_to_post),
                CURLOPT_POSTFIELDS => $data_to_post));

            $result = curl_exec($ch);

            if($errno = curl_errno($ch)) {
                $error_message = curl_strerror($errno);
                echo "cURL error ({$errno}):\n {$error_message}";
            }

            curl_close($ch);
*/



        }
    }
}


/**
 * Removes user entries with status 'archived' from drupals' flat_deposit_ui_upload_log table and fills it with data from fedora commons
 * @param $form
 * @param $form_state
 */
function flat_deposit_ui_commit_form_refresh_archived_submit($form, &$form_state)
{
    // deletes entries
    $del = db_delete('flat_deposit_ui_upload_log')
        ->condition('user_id', USER)
        ->condition('status', 'archived')
        ->execute();

    // Fedora commons database actions
    $tuque = islandora_get_tuque_connection();
    $api_a = $tuque->repository->api->a;
    $condition = "ownerId=" . USER;
    $results = $api_a->findObjects('query',$condition);

    module_load_include('inc', 'flat_deposit_ui' , '/inc/config');

    foreach ($results['results'] as $result) {
        $pid = $result['pid'];
        if (preg_match('/_CMD/', $pid)) {
            //Make entry on database
            $pid_data = $api_a->getObjectProfile($pid);
            $config = get_initial_bundle_profile();
            $config['user_id'] = USER;
            $config['bundle'] = $pid_data['objLabel'];
            $config['collection'] = 'Sandbox';
            $config['status'] = 'archived';
            $config['date_bundle_ingest'] = strtotime($pid_data['objCreateDate']);

            drupal_write_record('flat_deposit_ui_upload_log', $config);

        }
    }


}

