<?php
/**
 * Demonstrate a few mildly advanced topics with Forms API
 *
 * @version $Id$
 * @author FG Marand
 * @license GPL 2 or later
 */

function form_demo_menu()
{

  $items = array();
  $items['form_demo'] = array(
      'page callback'           => 'drupal_get_form',
      'page arguments' => array('form_demo_form'),
      'access callback' => TRUE,
      'title'              => t('Form demo'),
  );

  return $items;
}

function form_demo_form()
{
  $form = array();

  $form['fd_boxes'] = array
  (
      '#type'            => 'checkboxes',
      '#options'         => drupal_map_assoc(array ('a', 'b', 'c',)),
      '#default_value'   =>  array(0),
  );

  $form['submit'] = array
  (
      '#type'  => 'submit',
      '#value' => t('Test'),
  );

  return $form;
}

function form_demo_form_submit($form_id, $form_values)
{
    /**
     * Look at form_values: it only contains the keys to the fd_boxes array:
     * We're not supposed to use the captions for storage
     */
    // dsm($form_values);

    // Exclude unnecessary elements. This one comes from our form:
  unset($form_values['submit']);

  // But these ones are put in by Forms API and always there
  unset($form_values['form_id'], $form_values['op'], $form_values['form_token']);

// To be continued ...

// ... continuing
    foreach ($form_values as $key => $element)
    {
        variable_set($key, $element); // Serialized as necessary, so it will store an array
    }
}